---
- debug:
    msg: "oah-install of oah.kobman"

- name: Fetching io file for KOBman
  become: yes
  vars:
    clone_path: /home/vagrant/kobman_install.sh
  get_url:
    url: https://raw.githubusercontent.com/asa1997/KOBman/dist/dist/get.kobman.io
    dest: "{{ clone_path }}"

- name: Setting up permission
  become: yes
  command: "{{ item }}"
  with_items:
       - chmod 775 /home/vagrant/kobman_install.sh

# - name: Installing KOBman
#   # command: ./kobman_install.sh
#   shell: source /home/vagrant/kobman_install.sh
#        #- rm -rf kobman_install.sh

- name: Installing KOBman
  ansible.builtin.script: /home/vagrant/kobman_install.sh
  args:
    executable: /bin/bash


- name: Updating permission 
  shell: chmod 755 /home/vagrant/.kobman/bin/kobman-init.sh

- name: Source KOBman environment 
  become: no 
  shell: . ~/.bashrc  && /home/vagrant/.kobman/bin/kobman-init.sh
